---
- name: "Sync common environment"
  synchronize: 
    src: "files/"
    dest: "{{ ansible_user_dir }}/"
    recursive: yes
    rsync_opts:
      - "--no-motd"
      - "--exclude=.brewrc.d"

- name: "Sync .brewrc.d to Darwin environments"
  when: ansible_os_family == 'Darwin'
  synchronize: 
    src: "files/.brewrc.d"
    dest: "{{ ansible_user_dir }}/"
    recursive: yes