---
- name: Ensure configured homebrew packages are installed.
  homebrew: "name={{ item }} state=present"
  with_items: homebrew_control_installed_packages
  when: homebrew_control_installed_packages