---
- name: "Sanity check for SUSE Environment"
  ping:

- name: Install Ansible repository
  zypper_repository: repo=http://download.opensuse.org/repositories/systemsmanagement/openSUSE_13.2/systemsmanagement.repo
  sudo: yes
  tags:
    - suse-prereqs
    - suse-ansible-repo

- name: Install Ansible and other prereqs
  zypper: name={{ item }} state=present
  with_items:
    - ansible
    - zsh
    - keychain
    - vim
  sudo: yes
  tags:
    - suse-prereqs


- name: Change shell to ZSH
  user: name={{ ansible_user_id }}
        groups=users
        append=yes
        shell=/usr/bin/zsh
  sudo: yes
  tags:
    - suse-config-shell

- name: Set default key for user
  user: name={{ ansible_user_id }}
        groups=users
        append=yes
        generate_ssh_key=yes
        ssh_key_bits=2048
        ssh_key_type=rsa
        ssh_key_file=.ssh/key-{{ansible_hostname}}-{{ansible_date_time.year}}{{ansible_date_time.month}}{{ansible_date_time.day}}
  sudo: yes
  tags:
    - suse-config-shell