---
- name: "Sanity check for SUSE Environment"
  ping:

# - name: "Install prereq packages"
#   apt: pkg={{item}} state=installed
#   with_items:
#     - software-properties-common 
#     - nfs-kernel-server 
#     - nfs-common
#     - portmap
#     - zsh
#     - keychain
#     - vim
#   sudo: yes

- name: "Install Oracle Virtualbox GPG key"
  rpm_key: state=present key=https://www.virtualbox.org/download/oracle_vbox.asc 
  sudo: yes
  tags:
    - suse-virtualbox


- name: Fetch latest Oracle Virtualbox Installer
  get_url:  url=http://download.virtualbox.org/virtualbox/5.0.4/VirtualBox-{{ virtualbox_verison | default('5.0-5.0.4_102546_fedora18-1') }}.{{ ansible_architecture }}.rpm
            dest=/tmp/VirtualBox-{{ virtualbox_verison | default('5.0-5.0.4_102546_fedora18-1') }}.{{ ansible_architecture }}.rpm
            mode=0644
  tags:
    - suse-virtualbox

- name: Run latest Oracle Virtualbox Installer
  zypper: name=/tmp/VirtualBox-{{ virtualbox_verison | default('5.0-5.0.4_102546_fedora18-1') }}.{{ ansible_architecture }}.rpm
          state=present
  sudo: yes
  tags:
    - suse-virtualbox

# - name: "Add repository for latest Oracle Virtualbox (5.0.x)"
#   apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian vivid contrib' state=present
#   sudo: yes

# - name: "Add repository for latest Ansible"
#   apt_repository: repo='ppa:ansible/ansible' state=present
#   sudo: yes

# - name: "Update cache"
#   apt: update_cache=yes
#   sudo: yes

# - name: Install Virtualbox and Ansible
#   apt: pkg={{item}} state=installed
#   with_items:
#     - virtualbox-5.0
#     - ansible
#   sudo: yes

- name: Fetch Vagrant installer
  get_url:  url=https://dl.bintray.com/mitchellh/vagrant/vagrant_{{ vagrant_version | default('1.7.4')}}_{{ ansible_architecture }}.rpm  
            dest=/tmp/vagrant_{{ vagrant_version | default('1.7.4')}}_{{ ansible_architecture }}.rpm 
            mode=0644
  tags:
    - suse-vagrant

- name: Run Vagrant installer
  zypper:  name=/tmp/vagrant_{{ vagrant_version | default('1.7.4')}}_{{ ansible_architecture }}.rpm
        state=present
  sudo: yes
  tags:
    - suse-vagrant


- name: Install Ansible repository
  zypper_repository: repo=http://download.opensuse.org/repositories/systemsmanagement/openSUSE_13.2/systemsmanagement.repo
  sudo: yes
  tags:
    - suse-prereqs
    - suse-ansible-repo

- name: Install Ansible and other prereqs
  zypper: name={{ item }} state=present
  with_items:
    - ansible
    - zsh
    - keychain
    - vim
  sudo: yes
  tags:
    - suse-prereqs


- name: Change shell to ZSH
  user: name={{ ansible_user_id }}
        groups=users
        append=yes
        shell=/usr/bin/zsh
  sudo: yes
  tags:
    - suse-config-shell

- name: Set default key for user
  user: name={{ ansible_user_id }}
        groups=users
        append=yes
        generate_ssh_key=yes
        ssh_key_bits=2048
        ssh_key_type=rsa
        ssh_key_file=.ssh/key-{{ansible_hostname}}-{{ansible_date_time.year}}{{ansible_date_time.month}}{{ansible_date_time.day}}
  sudo: yes
  tags:
    - suse-config-shell